version: '3.8'
services:
    appgate-calculadora-rest:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        expose:
            - 8080
        volumes:
            - ./app:/home